(include-file "include/boolean.lfe")
(include-file "include/numeric.lfe")
(include-file "include/list.lfe")
(include-file "include/tuple.lfe")
(include-file "include/set.lfe")
(include-file "include/dictionary.lfe")
(include-file "include/thread.lfe")
